#!/usr/bin/env python3

import numpy
import ruamel.yaml
import sys
from python_to_numpy import python_to_numpy

EXIT_SUCCESS = 0
EXIT_FAILURE = 1

if len(sys.argv) < 2:
  print(f'usage: {sys.argv[0]:s} gamma_decode_fit_in.yml [name]')
  sys.exit(EXIT_FAILURE)
gamma_decode_fit_in = sys.argv[1]
name = sys.argv[2] if len(sys.argv) >= 3 else 'gamma_decode'

yaml = ruamel.yaml.YAML(typ = 'safe')
#numpy.set_printoptions(threshold = numpy.inf)

with open(gamma_decode_fit_in) as fin:
  gamma_decode_fit = python_to_numpy(yaml.load(fin))
p = gamma_decode_fit['p']
err = gamma_decode_fit['err']
exp0 = gamma_decode_fit['exp0']
post_factor = gamma_decode_fit['post_factor']

print(
  '''// generated by ../prepare/gamma_decode_gen_c_float.py

#include <math.h>
#include "gamma_decode.h"

static float post_factor[] = {{{0:s}
}};

// returns approximation to:
//   x < 12.92f * .0031308f ? x / 12.92f : powf((x + .055f) / 1.055f, 2.4f)
// allowed domain (-inf, 1.945), recommended domain [-epsilon, 1 + epsilon]
// do not call with argument >= 1.945 due to table lookup overflow (unchecked)
// minimax error is up to {1:f} on domain [.445, .945]
float {2:s}(float x) {{
  if (x < {3:.8e}f)
    return x * {4:.8e}f;
  int exp;
  x = frexpf(x + .055f, &exp);
  float y = {5:.8e}f;
{6:s}  return y * post_factor[exp + {7:d}];
}}

#ifdef STANDALONE
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {{
  if (argc < 2) {{
    printf(
      "usage: %s x\\n"
        "x = gamma encoded intensity, calculates linear intensity\\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }}
  float x = atof(argv[1]);

  float y = {8:s}(x);
  printf("gamma encoded %.6f -> linear %.6f\\n", x, y);

  return EXIT_SUCCESS;
}}
#endif'''.format(
    ','.join(
      [
        f'\n  {post_factor[i]:.8e}f'
        for i in range(post_factor.shape[0])
      ]
    ),
    err,
    name,
    12.92 * .0031308,
    1. / 12.92,
    p[-1],
    ''.join(
      [
        '  y = y * x {0:s} {1:.8e}f;\n'.format(
          '-' if p[i] < 0. else '+',
          abs(p[i])
        )
        for i in range(p.shape[0] - 2, -1, -1)
      ]
    ),
    -exp0,
    name
  )
)
