#!/usr/bin/env python3

import math
import numpy
import poly

ORDER = 3
EPSILON = 1e-8

# independent variable in 16:16 fixed point
KELV_EXP = -16
KELV_MIN = 1000.
KELV_MAX = 15000.

# results in 2:30 fixed point
U_EXP = -30
V_EXP = -30

# find exponents of coefficients and intermediate results, then decide
# on the shift amounts to align each intermediate result with next stage
# (the shift also removes the effect of the independent variable exponent)
# return the aligned cofficients, the shifts, and exponent of final result
def process(p, a, b, independent_exp, bits):
  intermediate_exp = poly.intermediate_exp(p, a, b, EPSILON) - bits
  #print('intermediate_exp', intermediate_exp)
  shr = intermediate_exp[:-1] - intermediate_exp[1:] - independent_exp
  #print('shr', shr)
  return numpy.ldexp(p, -intermediate_exp), shr, intermediate_exp[0]

# if we round the coefficients to integer as-is, the algorithm would be
#   y = c[-1]
#   y = round(ldexp(y * x, -shr[-1])) + c[-2]
#   y = round(ldexp(y * x, -shr[-2])) + c[-3]
#   ...
# or, if we move the coefficients inside the round() then it would be
#   y = c[-1]
#   y = round(ldexp(y * x, -shr[-1]) + c[-2])
#   y = round(ldexp(y * x, -shr[-2]) + c[-3])
#   ...
# this lets us add an offset of .5 to each coefficient and use floor()
#   y = c[-1]
#   y = floor(ldexp(y * x, -shr[-1]) + c[-2])
#   y = floor(ldexp(y * x, -shr[-2]) + c[-3])
#   ...
# and we then move coefficients inside ldexp(), shifting to compensate
#   y = c[-1]
#   y = floor(ldexp(y * x + c[-2], -shr[-1])
#   y = floor(ldexp(y * x + c[-3], -shr[-2])
#   ...
# then provided the shr is at least 1, the coefficients can be integer
def quantize(c, shr):
  assert numpy.all(shr >= 1)
  c = numpy.copy(c)
  c[:-1] = numpy.ldexp(c[:-1] + .5, shr)
  return numpy.round(c).astype(numpy.int64)
 
p_u_num = numpy.array(
  [.860117757, 1.54118254e-4, 1.28641212e-7],
  numpy.double
)
c_u_num, shr_u_num, exp_u_num = process(
  p_u_num,
  KELV_MIN,
  KELV_MAX,
  KELV_EXP,
  31
)
c_u_num = quantize(c_u_num, shr_u_num)

p_u_denom = numpy.array(
  [1., 8.42420235e-4, 7.08145163e-7],
  numpy.double
)
c_u_denom, shr_u_denom, exp_u_denom = process(
  p_u_denom,
  KELV_MIN,
  KELV_MAX,
  KELV_EXP,
  31
)
c_u_denom = quantize(c_u_denom, shr_u_denom)

p_v_num = numpy.array(
  [.317398726, 4.22806245e-5, 4.20481691e-8],
  numpy.double
)
c_v_num, shr_v_num, exp_v_num = process(
  p_v_num,
  KELV_MIN,
  KELV_MAX,
  KELV_EXP,
  31
)
c_v_num = quantize(c_v_num, shr_v_num)

p_v_denom = numpy.array(
  [1., -2.89741816e-5, 1.61456053e-7],
  numpy.double
)
c_v_denom, shr_v_denom, exp_v_denom = process(
  p_v_denom,
  KELV_MIN,
  KELV_MAX,
  KELV_EXP,
  31
)
c_v_denom = quantize(c_v_denom, shr_v_denom)

# make sure we can divide u_num by u_denom, v_num by v_denom
#  maximum we can shift by is 32, but allow one less for rounding
div_shift_u = exp_u_num - exp_u_denom - U_EXP
assert div_shift_u >= 0 and div_shift_u < 32
div_shift_v = exp_v_num - exp_v_denom - V_EXP
assert div_shift_v >= 0 and div_shift_v < 32

print(
  '''// generated by ../prepare/kelv_to_uv_gen_c_fixed.py

#include <assert.h>
#include <math.h>
#include "kelv_to_uv.h"

#define UV_u 0
#define UV_v 1
#define N_UV 2

// kelv in 16:16 fixed point, results in 2:30 fixed point
void kelv_to_uv(int32_t kelv, int32_t *uv) {{
  // validate inputs, allowing a little slack
  assert(kelv >= 0x{0:x} && kelv < 0x{1:x});

  // find the approximate (u, v) chromaticity of the given Kelvin value
  // see http://en.wikipedia.org/wiki/Planckian_locus#Approximation (Krystek)
  // we evaluate this with Horner's rule for better numerical stability
  int32_t u = 0x{2:x};
  u = (int32_t)(((int64_t)u * kelv + 0x{3:x}LL) >> {4:d});
  u = (int32_t)(((int64_t)u * kelv + 0x{5:x}LL) >> {6:d});
  int32_t u_denom = 0x{7:x};
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x{8:x}LL) >> {9:d});
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x{10:x}LL) >> {11:d});
  uv[UV_u] = (int32_t)((((int64_t)u << {12:d}) / u_denom + 1) >> 1);

  int32_t v = 0x{13:x};
  v = (int32_t)(((int64_t)v * kelv + 0x{14:x}LL) >> {15:d});
  v = (int32_t)(((int64_t)v * kelv + 0x{16:x}LL) >> {17:d});
  int32_t v_denom = 0x{18:x};
  v_denom = (int32_t)(((int64_t)v_denom * kelv - 0x{19:x}LL) >> {20:d});
  v_denom = (int32_t)(((int64_t)v_denom * kelv + 0x{21:x}LL) >> {22:d});
  uv[UV_v] = (int32_t)((((int64_t)v << {23:d}) / v_denom + 1) >> 1);
}}

#ifdef STANDALONE
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {{
  if (argc < 2) {{
    printf(
      "usage: %s kelv\\n"
        "kelv = colour temperature in degrees Kelvin\\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }}
  int32_t kelv = (int32_t)roundf(ldexpf(atof(argv[1]), 16));

  int32_t uv[N_UV];
  kelv_to_uv(kelv, uv);
  printf(
    "kelv %.3f -> uv (%.6f, %.6f)\\n",
    ldexpf(kelv, -16),
    ldexpf(uv[UV_u], -30),
    ldexpf(uv[UV_v], -30)
  );

  return EXIT_SUCCESS;
}}
#endif'''.format(
    int(round(math.ldexp(KELV_MIN * (1. - EPSILON), -KELV_EXP))),
    int(round(math.ldexp(KELV_MAX * (1. + EPSILON), -KELV_EXP))),
    c_u_num[2],
    c_u_num[1],
    shr_u_num[1],
    c_u_num[0],
    shr_u_num[0],
    c_u_denom[2],
    c_u_denom[1],
    shr_u_denom[1],
    c_u_denom[0],
    shr_u_denom[0],
    div_shift_u + 1,
    c_v_num[2],
    c_v_num[1],
    shr_v_num[1],
    c_v_num[0],
    shr_v_num[0],
    c_v_denom[2],
    -c_v_denom[1],
    shr_v_denom[1],
    c_v_denom[0],
    shr_v_denom[0],
    div_shift_v + 1
  )
)
