#!/usr/bin/env python3

# Copyright (c) 2020 Nick Downing
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import math
import mpmath
import numpy
from utils.poly_fixed import poly_fixed

EPSILON = 1e-6

mpmath.mp.prec = 106

# independent variable in 16:16 fixed point
KELV_EXP = -16
KELV_MIN = 1000.
KELV_MAX = 15000.

# results in 2:30 fixed point
UV_EXP = -30

p_u_num, p_shr_u_num, p_exp_u_num = poly_fixed(
  mpmath.matrix([.860117757, 1.54118254e-4, 1.28641212e-7])
  KELV_MIN,
  KELV_MAX,
  KELV_EXP,
  31
)
p_u_denom, p_shr_u_denom, p_exp_u_denom = poly_fixed(
  mpmath.matrix([1., 8.42420235e-4, 7.08145163e-7])
  KELV_MIN,
  KELV_MAX,
  KELV_EXP,
  31
)
p_v_num, p_shr_v_num, p_exp_v_num = poly_fixed(
  mpmath.matrix([.317398726, 4.22806245e-5, 4.20481691e-8]),
  KELV_MIN,
  KELV_MAX,
  KELV_EXP,
  31
)
p_v_denom, p_shr_v_denom, p_exp_v_denom = poly_fixed(
  mpmath.matrix([1., -2.89741816e-5, 1.61456053e-7]),
  KELV_MIN,
  KELV_MAX,
  KELV_EXP,
  31
)

# make sure we can divide u_num by u_denom and v_num by v_denom
# maximum we can shift by is 32, but allow one less for rounding
div_shl_u = p_exp_u_num - p_exp_u_denom - UV_EXP
assert div_shl_u >= 0 and div_shl_u < 32
div_shl_v = p_exp_v_num - p_exp_v_denom - UV_EXP
assert div_shl_v >= 0 and div_shl_v < 32

print(
  '''// generated by ../prepare/kelv_to_uv_gen_c_fixed.py

// Copyright (c) 2020 Nick Downing
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

#include <assert.h>
#include "kelv_to_uv.h"

#define UV_u 0
#define UV_v 1
#define N_UV 2

// kelv in 16:16 fixed point, results in 2:30 fixed point
void kelv_to_uv(int32_t kelv, int32_t *uv) {{
  // validate inputs, allowing a little slack
  assert(kelv >= 0x{0:x} && kelv < 0x{1:x});

  // find the approximate (u, v) chromaticity of the given Kelvin value
  // see http://en.wikipedia.org/wiki/Planckian_locus#Approximation (Krystek)
  // we evaluate this with Horner's rule for better numerical stability
  int32_t u = 0x{2:x};
  u = (int32_t)(((int64_t)u * kelv + 0x{3:x}LL) >> {4:d});
  u = (int32_t)(((int64_t)u * kelv + 0x{5:x}LL) >> {6:d});
  int32_t u_denom = 0x{7:x};
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x{8:x}LL) >> {9:d});
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x{10:x}LL) >> {11:d});
  uv[UV_u] = (int32_t)((((int64_t)u << {12:d}) / u_denom + 1) >> 1);

  int32_t v = 0x{13:x};
  v = (int32_t)(((int64_t)v * kelv + 0x{14:x}LL) >> {15:d});
  v = (int32_t)(((int64_t)v * kelv + 0x{16:x}LL) >> {17:d});
  int32_t v_denom = 0x{18:x};
  v_denom = (int32_t)(((int64_t)v_denom * kelv - 0x{19:x}LL) >> {20:d});
  v_denom = (int32_t)(((int64_t)v_denom * kelv + 0x{21:x}LL) >> {22:d});
  uv[UV_v] = (int32_t)((((int64_t)v << {23:d}) / v_denom + 1) >> 1);
}}

#ifdef STANDALONE
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {{
  if (argc < 2) {{
    printf(
      "usage: %s kelv\\n"
        "kelv = colour temperature in degrees Kelvin\\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }}
  int32_t kelv = (int32_t)roundf(ldexpf(atof(argv[1]), 16));

  int32_t uv[N_UV];
  kelv_to_uv(kelv, uv);
  printf(
    "kelv %.3f -> uv (%.6f, %.6f)\\n",
    ldexpf(kelv, -16),
    ldexpf(uv[UV_u], -30),
    ldexpf(uv[UV_v], -30)
  );

  return EXIT_SUCCESS;
}}
#endif'''.format(
    int(round(math.ldexp(KELV_MIN * (1. - EPSILON), -KELV_EXP))),
    int(round(math.ldexp(KELV_MAX * (1. + EPSILON), -KELV_EXP))),
    p_u_num[2],
    p_u_num[1],
    p_shr_u_num[1],
    p_u_num[0],
    p_shr_u_num[0],
    p_u_denom[2],
    p_u_denom[1],
    p_shr_u_denom[1],
    p_u_denom[0],
    p_shr_u_denom[0],
    div_shl_u + 1,
    p_v_num[2],
    p_v_num[1],
    p_shr_v_num[1],
    p_v_num[0],
    p_shr_v_num[0],
    p_v_denom[2],
    -p_v_denom[1],
    p_shr_v_denom[1],
    p_v_denom[0],
    p_shr_v_denom[0],
    div_shl_v + 1
  )
)
