// generated by ../prepare/gamma_decode_gen_c_fixed.py

// Copyright (c) 2020 Nick Downing
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

#include "gamma_decode.h"

static int32_t post_factor[] = {
  0x1bdb8d,
  0x93088c,
  0x3080c00,
  0x10000000,
  0x5472d14f
};

// argument and result in 2:30 fixed point
// returns approximation to:
//   x < 12.92f * .0031308f ? x / 12.92f : powf((x + .055f) / 1.055f, 2.4f)
// allowed domain [-2, 1.945), recommended domain [-epsilon, 1 + epsilon)
// minimax error is up to 1.187446e-08 relative
int32_t gamma_decode(int32_t x) {
  if (x < 0x296bb54)
    return (int32_t)((x * 0x4f41c885LL + 0x200000000LL) >> 34);
  x += 0x3851eb8;
  int exp = 4;
  if ((x & 0x78000000) == 0) {
    x <<= 4;
    exp -= 4;
  }
  if ((x & 0x60000000) == 0) {
    x <<= 2;
    exp -= 2;
  }
  if ((x & 0x40000000) == 0) {
    x <<= 1;
    exp -= 1;
  }
  int32_t y = -0xd27b6bc;
  y = (int32_t)(((int64_t)y * x + 0x284a35d49f297200LL) >> 32);
  y = (int32_t)(((int64_t)y * x - 0x3bc2a4874c784e00LL) >> 33);
  y = (int32_t)(((int64_t)y * x + 0x2668cf8cc4ea1800LL) >> 31);
  y = (int32_t)(((int64_t)y * x + 0x1eef110d2b441700LL) >> 31);
  y = (int32_t)(((int64_t)y * x - 0x2816bfcacfce600LL) >> 31);
  y = (int32_t)(((int64_t)y * x + 0x2bc0f3d9c2f740LL) >> 31);
  return (int32_t)(((int64_t)y * post_factor[exp] + 0x10000000LL) >> 29);
}

#ifdef STANDALONE
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s x\n"
        "x = gamma encoded intensity, calculates linear intensity\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  int32_t x = (int32_t)roundf(ldexpf(atof(argv[1]), 30));

  int32_t y = gamma_decode(x);
  printf("gamma encoded %.6f -> linear %.6f\n", ldexpf(x, -30), ldexpf(y, -30));

  return EXIT_SUCCESS;
}
#endif
