// generated by ../prepare/gamma_encode_gen_c_fixed.py

// Copyright (c) 2020 Nick Downing
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

#include "gamma_encode.h"

static int32_t post_factor[] = {
  0x6597fa9,
  0x879c7c9,
  0xb504f33,
  0xf1a1bf4,
  0x1428a2fa,
  0x1ae89f99,
  0x23eb3588,
  0x2ff221af,
  0x40000000,
  0x556e0424
};

// argument and result in 2:30 fixed point
// returns approximation to:
//   x < .0031308f ? x * 12.92f : powf(x, 1.f / 2.4f) * 1.055f - .055f
// allowed domain [-2, 2), recommended domain [-epsilon, 1 + epsilon)
// minimax error is up to 3.018057e-08 relative
int32_t gamma_encode(int32_t x) {
  if (x < 0x334b87)
    return (int32_t)((x * 0x675c28f6LL + 0x4000000LL) >> 27);
  int exp = 9;
  if ((x & 0x7f800000) == 0) {
    x <<= 8;
    exp -= 8;
  }
  if ((x & 0x78000000) == 0) {
    x <<= 4;
    exp -= 4;
  }
  if ((x & 0x60000000) == 0) {
    x <<= 2;
    exp -= 2;
  }
  if ((x & 0x40000000) == 0) {
    x <<= 1;
    exp -= 1;
  }
  int32_t y = 0x14da6e8f;
  y = (int32_t)(((int64_t)y * x - 0x3f9c38df9f4e9400LL) >> 33);
  y = (int32_t)(((int64_t)y * x + 0x2a9acc5cc6906a00LL) >> 32);
  y = (int32_t)(((int64_t)y * x - 0x210364171bce6400LL) >> 31);
  y = (int32_t)(((int64_t)y * x + 0x210223c34866da00LL) >> 31);
  y = (int32_t)(((int64_t)y * x - 0x1717e7eea7ecb900LL) >> 30);
  y = (int32_t)(((int64_t)y * x + 0x1d9bb042c95c5100LL) >> 30);
  y = (int32_t)(((int64_t)y * x + 0x851b807cae8ec00LL) >> 31);
  return (int32_t)(((int64_t)y * post_factor[exp] - 0xe147adf47ae148LL) >> 30);
}

#ifdef STANDALONE
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s x\n"
        "x = gamma encoded intensity, calculates linear intensity\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  int32_t x = (int32_t)roundf(ldexpf(atof(argv[1]), 30));

  int32_t y = gamma_encode(x);
  printf("gamma encoded %.6f -> linear %.6f\n", ldexpf(x, -30), ldexpf(y, -30));

  return EXIT_SUCCESS;
}
#endif
