// generated by ../prepare/kelv_to_uv_gen_c_fixed.py

#include <assert.h>
#include "kelv_to_uv.h"

#define UV_u 0
#define UV_v 1
#define N_UV 2

// kelv in 16:16 fixed point, results in 2:30 fixed point
void kelv_to_uv(int32_t kelv, int32_t *uv) {
  // validate inputs, allowing a little slack
  assert(kelv >= 0x3e7ffbe && kelv < 0x3a9803d7);

  // find the approximate (u, v) chromaticity of the given Kelvin value
  // see http://en.wikipedia.org/wiki/Planckian_locus#Approximation (Krystek)
  // we evaluate this with Horner's rule for better numerical stability
  int32_t u = 0x114414;
  u = (int32_t)(((int64_t)u * kelv + 0x50cd6ee29ab2LL) >> 28);
  u = (int32_t)(((int64_t)u * kelv + 0x6e1856d2830eLL) >> 22);
  int32_t u_denom = 0x17c2ec;
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x6e6af2b7b66cLL) >> 27);
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x400000400000LL) >> 23);
  uv[UV_u] = (int32_t)((((int64_t)u << 29) / u_denom + 1) >> 1);

  int32_t v = 0x16930e;
  v = (int32_t)(((int64_t)v * kelv + 0x58ab4cc88e62LL) >> 29);
  v = (int32_t)(((int64_t)v * kelv + 0x51410b0bf64aLL) >> 21);
  int32_t v_denom = 0xad5cb4;
  v_denom = (int32_t)(((int64_t)v_denom * kelv - 0x79864a64c480LL) >> 32);
  v_denom = (int32_t)(((int64_t)v_denom * kelv + 0x400000100000LL) >> 21);
  uv[UV_v] = (int32_t)((((int64_t)v << 29) / v_denom + 1) >> 1);
}

#ifdef STANDALONE
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s kelv\n"
        "kelv = colour temperature in degrees Kelvin\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  int32_t kelv = (int32_t)roundf(ldexpf(atof(argv[1]), 16));

  int32_t uv[N_UV];
  kelv_to_uv(kelv, uv);
  printf(
    "kelv %.3f -> uv (%.6f, %.6f)\n",
    ldexpf(kelv, -16),
    ldexpf(uv[UV_u], -30),
    ldexpf(uv[UV_v], -30)
  );

  return EXIT_SUCCESS;
}
#endif
