// generated by ../prepare/kelv_to_uv_gen_c_fixed.py

#include <assert.h>
#include <math.h>
#include "kelv_to_uv.h"

#define UV_u 0
#define UV_v 1
#define N_UV 2

// kelv in 16:16 fixed point, results in 2:30 fixed point
void kelv_to_uv(int32_t kelv, int32_t *uv) {
  // validate inputs, allowing a little slack
  assert(kelv >= 0x3e7ffff && kelv < 0x3a98000a);

  // find the approximate (u, v) chromaticity of the given Kelvin value
  // see http://en.wikipedia.org/wiki/Planckian_locus#Approximation (Krystek)
  // we evaluate this with Horner's rule for better numerical stability
  int32_t u = 0x45105045;
  u = (int32_t)(((int64_t)u * kelv + 0x143359baa6ac870LL) >> 30);
  u = (int32_t)(((int64_t)u * kelv + 0x6e1856d2830e58LL) >> 30);
  int32_t u_denom = 0x5f0baeba;
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x1b9abbafed9aed0LL) >> 30);
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x20000020000000LL) >> 30);
  uv[UV_u] = (int32_t)((((int64_t)u << 29) / u_denom + 1) >> 1);

  int32_t v = 0x5a4c39b6;
  v = (int32_t)(((int64_t)v * kelv + 0x162acf3423988f0LL) >> 30);
  v = (int32_t)(((int64_t)v * kelv + 0xa2821617ec93c8LL) >> 30);
  int32_t v_denom = 0x56ae59d8;
  v_denom = (int32_t)(((int64_t)v_denom * kelv - 0x3cc3651262400aLL) >> 30);
  v_denom = (int32_t)(((int64_t)v_denom * kelv + 0x80000020000000LL) >> 30);
  uv[UV_v] = (int32_t)((((int64_t)v << 29) / v_denom + 1) >> 1);
}

#ifdef STANDALONE
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s kelv\n"
        "kelv = colour temperature in degrees Kelvin\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  int32_t kelv = (int32_t)roundf(ldexpf(atof(argv[1]), 16));

  int32_t uv[N_UV];
  kelv_to_uv(kelv, uv);
  printf(
    "kelv %.3f -> uv (%.6f, %.6f)\n",
    ldexpf(kelv, -16),
    ldexpf(uv[UV_u], -30),
    ldexpf(uv[UV_v], -30)
  );

  return EXIT_SUCCESS;
}
#endif
