// generated by ../prepare/kelv_to_uv_gen_c_fixed.py

#include <assert.h>
#include <math.h>
#include "kelv_to_uv.h"

#define UV_u 0
#define UV_v 1
#define N_UV 2

// kelv in 16:16 fixed point, uv in 2:32 fixed point
void kelv_to_uv(int32_t kelv, int32_t *uv) {
  // validate inputs, allowing a little slack
  assert(kelv >= 0x3e7fff9 && kelv < 0x3a980007);

  // find the approximate (u, v) chromaticity of the given Kelvin value
  // see http://en.wikipedia.org/wiki/Planckian_locus#Approximation (Krystek)
  // we evaluate this with Horner's rule for better numerical stability
  int32_t u = 0x22883;
  u = (int32_t)(((int64_t)u * kelv + 0xa19aedc5356LL) >> 26);
  u = (int32_t)(((int64_t)u * kelv + 0x370c2d594187LL) >> 26);
  int32_t u_denom = 0xbe176;
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x3735795bdb36LL) >> 26);
  u_denom = (int32_t)(((int64_t)u_denom * kelv + 0x400002000000LL) >> 26);
  uv[UV_u] = (int32_t)((((int64_t)u << 31) / u_denom + 1) >> 1);

  int32_t v = 0xb498;
  v = (int32_t)(((int64_t)v * kelv + 0x2c55be64473LL) >> 26);
  v = (int32_t)(((int64_t)v * kelv + 0x145044befd92LL) >> 26);
  int32_t v_denom = 0x2b573;
  v_denom = (int32_t)(((int64_t)v_denom * kelv - 0x1e619299312LL) >> 26);
  v_denom = (int32_t)(((int64_t)v_denom * kelv + 0x400002000000LL) >> 26);
  uv[UV_v] = (int32_t)((((int64_t)v << 31) / v_denom + 1) >> 1);
}

#ifdef STANDALONE
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s kelv\n"
        "kelv = colour temperature in degrees Kelvin\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  int32_t kelv = (int32_t)roundf(ldexpf(atof(argv[1]), 16));

  int32_t uv[N_UV];
  kelv_to_uv(kelv, uv);
  printf(
    "kelv %.3f -> uv (%.6f, %.6f)\n",
    ldexpf(kelv, -16),
    ldexpf(uv[UV_u], -30),
    ldexpf(uv[UV_v], -30)
  );

  return EXIT_SUCCESS;
}
#endif

