// generated by ../prepare/mired_to_rgb_gen_c_fixed.py

#include <assert.h>
#include "mired_to_rgb.h"

#define RGB_RED 0
#define RGB_GREEN 1
#define RGB_BLUE 2
#define N_RGB 3

#define EPSILON 0x40

void mired_to_rgb(int32_t mired, int32_t *rgb) {
  // validate inputs, allowing a little slack
  assert(mired >= 0x42aaab - EPSILON && mired < 0x3e80000 + EPSILON);

  // calculate red channel
  int32_t r;
  if (mired < 0x99038b) {
    r = 0x87f6f;
    r = (int32_t)(((int64_t)r * mired + 0x49e236dcf637LL) >> 23);
    r = (int32_t)(((int64_t)r * mired + 0x5474dbe8e3e6LL) >> 25);
    r = (int32_t)(((int64_t)r * mired + 0x4a8cb70590a3LL) >> 17);
  }
  else {
    r = 0x40000000;
  }
  rgb[RGB_RED] = r;

  // calculate green channel
  int32_t g;
  if (mired < 0x996336) {
    g = -0xde1d5;
    g = (int32_t)(((int64_t)g * mired + 0x5e568aee2a2cLL) >> 24);
    g = (int32_t)(((int64_t)g * mired + 0x465d2bf77ce4LL) >> 25);
    g = (int32_t)(((int64_t)g * mired + 0x587d7da76da5LL) >> 17);
  }
  else {
    g = -0x6860d;
    g = (int32_t)(((int64_t)g * mired + 0x421348f4c564LL) >> 26);
    g = (int32_t)(((int64_t)g * mired - 0x45dd9093d654LL) >> 25);
    g = (int32_t)(((int64_t)g * mired + 0x5606d61fdd71LL) >> 25);
    g = (int32_t)(((int64_t)g * mired - 0x5cd3f252cb4bLL) >> 25);
    g = (int32_t)(((int64_t)g * mired + 0x5438f89082cbLL) >> 16);
  }
  rgb[RGB_GREEN] = g;

  // calculate blue channel
  int32_t b;
  if (mired < 0x98abb5) {
    b = 0x40000000;
  }
  else if (mired < 0x20e061d) {
    b = -0x6c6d7;
    b = (int32_t)(((int64_t)b * mired - 0x550ae384e8abLL) >> 27);
    b = (int32_t)(((int64_t)b * mired + 0x6c853c908fd8LL) >> 26);
    b = (int32_t)(((int64_t)b * mired - 0x5a2600a53c66LL) >> 25);
    b = (int32_t)(((int64_t)b * mired + 0x49b8c2130431LL) >> 23);
    b = (int32_t)(((int64_t)b * mired - 0x7d3c4975a2dcLL) >> 23);
    b = (int32_t)(((int64_t)b * mired + 0x58feb1246c62LL) >> 21);
    b = (int32_t)(((int64_t)b * mired + 0x43662ef4e6a2LL) >> 17);
  }
  else {
    b = 0x0;
  }
  rgb[RGB_BLUE] = b;
}

#ifdef STANDALONE
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s mired\n"
        "mired = colour temperature in micro reciprocal degrees Kelvin\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  int32_t mired = (int32_t)roundf(ldexpf(atof(argv[1]), 16));

  int32_t rgb[N_RGB];
  mired_to_rgb(mired, rgb);
  printf(
    "mired %.3f -> RGB (%.6f, %.6f, %.6f)\n",
    ldexpf(mired, -16),
    ldexpf(rgb[RGB_RED], -30),
    ldexpf(rgb[RGB_GREEN], -30),
    ldexpf(rgb[RGB_BLUE], -30)
  );

  return EXIT_SUCCESS;
}
#endif
