// generated by ../prepare/mired_to_rgb_gen_c_fixed.py

// Copyright (c) 2020 Nick Downing
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

#include <assert.h>
#include "mired_to_rgb.h"

#define RGB_RED 0
#define RGB_GREEN 1
#define RGB_BLUE 2
#define N_RGB 3

#define EPSILON (1 << 6)

void mired_to_rgb(int32_t mired, int32_t *rgb) {
  // validate inputs, allowing a little slack
  assert(mired >= 0x42aaab - EPSILON && mired < 0x3e80000 + EPSILON);

  // calculate red channel
  int32_t r;
  if (mired < 0x99038b) {
    r = 0x87f70;
    r = (int32_t)(((int64_t)r * mired + 0x49e2362d0e2dLL) >> 23);
    r = (int32_t)(((int64_t)r * mired + 0x5474dc72f0c4LL) >> 25);
    r = (int32_t)(((int64_t)r * mired + 0x4a8cb6fcdd09LL) >> 17);
  }
  else {
    r = 0x40000000;
  }
  rgb[RGB_RED] = r;

  // calculate green channel
  int32_t g;
  if (mired < 0x996336) {
    g = -0xde1d3;
    g = (int32_t)(((int64_t)g * mired + 0x5e56890a0316LL) >> 24);
    g = (int32_t)(((int64_t)g * mired + 0x465d2cb3a3f2LL) >> 25);
    g = (int32_t)(((int64_t)g * mired + 0x587d7d9bad4fLL) >> 17);
  }
  else {
    g = -0x6860d;
    g = (int32_t)(((int64_t)g * mired + 0x42134e5f4640LL) >> 26);
    g = (int32_t)(((int64_t)g * mired - 0x45dd971ab65cLL) >> 25);
    g = (int32_t)(((int64_t)g * mired + 0x5606dd4a0270LL) >> 25);
    g = (int32_t)(((int64_t)g * mired - 0x5cd3f5ed42a5LL) >> 25);
    g = (int32_t)(((int64_t)g * mired + 0x5438f938f6c3LL) >> 16);
  }
  rgb[RGB_GREEN] = g;

  // calculate blue channel
  int32_t b;
  if (mired < 0x98b33d) {
    b = 0x40000000;
  }
  else if (mired < 0x20e0031) {
    b = -0x2af73c;
    b = (int32_t)(((int64_t)b * mired + 0x67b6c58afdb1LL) >> 27);
    b = (int32_t)(((int64_t)b * mired + 0x53f9cc0c25ecLL) >> 26);
    b = (int32_t)(((int64_t)b * mired - 0x6e6bd0b255bfLL) >> 25);
    b = (int32_t)(((int64_t)b * mired + 0x68b62005e4eaLL) >> 24);
    b = (int32_t)(((int64_t)b * mired - 0x5edb8344fcfbLL) >> 23);
    b = (int32_t)(((int64_t)b * mired + 0x41c8280233b1LL) >> 21);
    b = (int32_t)(((int64_t)b * mired + 0x60cc28c4a65cLL) >> 17);
  }
  else {
    b = 0x0;
  }
  rgb[RGB_BLUE] = b;
}

#ifdef STANDALONE
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s mired\n"
        "mired = colour temperature in micro reciprocal degrees Kelvin\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  int32_t mired = (int32_t)roundf(ldexpf(atof(argv[1]), 16));

  int32_t rgb[N_RGB];
  mired_to_rgb(mired, rgb);
  printf(
    "mired %.3f -> RGB (%.6f, %.6f, %.6f)\n",
    ldexpf(mired, -16),
    ldexpf(rgb[RGB_RED], -30),
    ldexpf(rgb[RGB_GREEN], -30),
    ldexpf(rgb[RGB_BLUE], -30)
  );

  return EXIT_SUCCESS;
}
#endif
