// generated by ../prepare/gamma_decode_gen_c_float.py

#include <math.h>
#include "gamma_decode.h"

static float post_factor[] = {
  6.80117628e-03f,
  3.58968236e-02f,
  1.89464571e-01f,
  1.00000000e+00f,
  5.27803164e+00f
};

// returns approximation to:
//   x < 12.92f * .0031308f ? x / 12.92f : powf((x + .055f) / 1.055f, 2.4f)
// allowed domain (-inf, 1.945), recommended domain [-epsilon, 1 + epsilon]
// do not call with argument >= 1.945 due to table lookup overflow (unchecked)
// minimax error is up to 8.360671e-09 on domain [.445, .945]
float gamma_decode(float x) {
  if (x < 4.04499360e-02f)
    return x * 7.73993808e-02f;
  int exp;
  x = frexpf(x + .055f, &exp);
  float y = -1.24606922e-02f;
  y = y * x + 7.69625871e-02f;
  y = y * x - 2.30250550e-01f;
  y = y * x + 5.97047280e-01f;
  y = y * x + 4.85016736e-01f;
  y = y * x - 3.96263437e-02f;
  y = y * x + 2.72643611e-03f;
  return y * post_factor[exp + 3];
}

#ifdef STANDALONE
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s x\n"
        "x = gamma encoded intensity, calculates linear intensity\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  float x = atof(argv[1]);

  float y = gamma_decode(x);
  printf("gamma encoded %.6f -> linear %.6f\n", x, y);

  return EXIT_SUCCESS;
}
#endif
