// generated by ../prepare/gamma_encode_gen_c_float.py

#include <math.h>
#include "gamma_encode.h"

static float post_factor[] = {
  9.92125657e-02f,
  1.32432887e-01f,
  1.76776695e-01f,
  2.35968578e-01f,
  3.14980262e-01f,
  4.20448208e-01f,
  5.61231024e-01f,
  7.49153538e-01f,
  1.00000000e+00f,
  1.33483985e+00f
};

// returns approximation to:
//   x < .0031308f ? x * 12.92f : powf(x, 1.f / 2.4f) * 1.055f - .055f
// allowed domain (-inf, 2), recommended domain [-epsilon, 1 + epsilon]
// do not call with argument >= 2 due to table lookup overflow (unchecked)
// minimax error is up to 2.088968e-08 on domain [.5, 1]
float gamma_encode(float x) {
  if (x < .0031308f)
    return x * 12.92f;
  int exp;
  x = frexpf(x, &exp);
  float y = 1.55108772e-01f;
  y = y * x - 9.53147799e-01f;
  y = y * x + 2.57243791e+00f;
  y = y * x - 4.01645737e+00f;
  y = y * x + 4.04619553e+00f;
  y = y * x - 2.85230330e+00f;
  y = y * x + 1.84237369e+00f;
  y = y * x + 2.60792591e-01f;
  return y * post_factor[exp + 8] - .055f;
}

#ifdef STANDALONE
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s x\n"
        "x = linear intensity, calculates gamma encoded intensity\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  float x = atof(argv[1]);

  float y = gamma_encode(x);
  printf("linear %.6f -> gamma encoded %.6f\n", x, y);

  return EXIT_SUCCESS;
}
#endif
