// generated by ../prepare/mired_to_rgb_gen_c_float.py

#include <assert.h>
#include "mired_to_rgb.h"

#define RGB_RED 0
#define RGB_GREEN 1
#define RGB_BLUE 2
#define N_RGB 3

#define EPSILON 1e-6

void mired_to_rgb(float mired, float *rgb) {
  // validate inputs, allowing a little slack
  assert(mired >= 6.66666667e+01f - EPSILON);
  assert(mired < 1.00000000e+03f + EPSILON);

  // calculate red channel
  float r;
  if (mired < 1.53014204e+02f) {
    r = 3.75228927e-09f;
    r = r * mired + 8.87539162e-06f;
    r = r * mired + 1.28143264e-03f;
    r = r * mired + 5.82677127e-01f;
  }
  else {
    r = 1.00000000e+00f;
  }

  // calculate green channel
  float g;
  if (mired < 1.53389630e+02f) {
    g = -3.17931513e-09f;
    g = g * mired + 5.60217181e-06f;
    g = g * mired + 1.07609628e-03f;
    g = g * mired + 6.91243100e-01f;
  }
  else {
    g = -2.89635037e-15f;
    g = g * mired + 7.50927775e-12f;
    g = g * mired + -8.13001568e-09f;
    g = g * mired + 5.12561864e-06f;
    g = g * mired + -2.83237945e-03f;
    g = g * mired + 1.31593131e+00f;
  }

  // calculate blue channel
  float b;
  if (mired < 1.52740534e+02f) {
    b = 1.00000000e+00f;
  }
  else if (mired < 5.25947680e+02f) {
    b = -2.77865265e-18f;
    b = b * mired + 4.58804157e-15f;
    b = b * mired + -2.67958426e-12f;
    b = b * mired + 4.88020519e-10f;
    b = b * mired + 1.20547997e-07f;
    b = b * mired + -6.02756590e-05f;
    b = b * mired + 4.20936766e-03f;
    b = b * mired + 1.23798676e+00f;
  }
  else {
    b = 0.00000000e+00f;
  }

  rgb[RGB_RED] = r;
  rgb[RGB_GREEN] = g;
  rgb[RGB_BLUE] = b;
}

#ifdef STANDALONE
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s mired\n"
        "mired = colour temperature in micro reciprocal degrees Kelvin\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  float mired = atof(argv[1]);

  float rgb[N_RGB];
  mired_to_rgb(mired, rgb);
  printf(
    "mired %.3f -> RGB (%.6f, %.6f, %.6f)\n",
    mired,
    rgb[RGB_RED],
    rgb[RGB_GREEN],
    rgb[RGB_BLUE]
  );

  return EXIT_SUCCESS;
}
#endif
