// generated by ../prepare/mired_to_rgb_gen_c_float.py

// Copyright (c) 2020 Nick Downing
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

#include <assert.h>
#include "mired_to_rgb.h"

#define RGB_RED 0
#define RGB_GREEN 1
#define RGB_BLUE 2
#define N_RGB 3

#define EPSILON 1e-6

void mired_to_rgb(float mired, float *rgb) {
  // validate inputs, allowing a little slack
  assert(mired >= 6.66666667e+01f * (1.f - EPSILON) && mired < 1.00000000e+03f * (1.f + EPSILON));

  // calculate red channel
  float r;
  if (mired < 1.53013835e+02f) {
    r = 3.95709693e-09f;
    r = r * mired + 8.80761568e-06f;
    r = r * mired + 1.28870351e-03f;
    r = r * mired + 5.82419274e-01f;
  }
  else {
    r = 1.00000000e+00f;
  }
  rgb[RGB_RED] = r;

  // calculate green channel
  float g;
  if (mired < 1.53387545e+02f) {
    g = -3.23218415e-09f;
    g = g * mired + 5.62298423e-06f;
    g = g * mired + 1.07366864e-03f;
    g = g * mired + 6.91329670e-01f;
  }
  else {
    g = -2.89707673e-15f;
    g = g * mired + 7.51190147e-12f;
    g = g * mired - 8.13342656e-09f;
    g = g * mired + 5.12759679e-06f;
    g = g * mired - 2.83288533e-03f;
    g = g * mired + 1.31597739e+00f;
  }
  rgb[RGB_GREEN] = g;

  // calculate blue channel
  float b;
  if (mired < 1.52700144e+02f) {
    b = 1.00000000e+00f;
  }
  else if (mired < 5.26000750e+02f) {
    b = -1.16458920e-18f;
    b = b * mired + 7.19659684e-16f;
    b = b * mired + 1.19336703e-12f;
    b = b * mired - 1.60683948e-09f;
    b = b * mired + 7.80160863e-07f;
    b = b * mired - 1.80926276e-04f;
    b = b * mired + 1.60600243e-02f;
    b = b * mired + 7.56230445e-01f;
  }
  else {
    b = 0.00000000e+00f;
  }
  rgb[RGB_BLUE] = b;
}

#ifdef STANDALONE
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char **argv) {
  if (argc < 2) {
    printf(
      "usage: %s mired\n"
        "mired = colour temperature in micro reciprocal degrees Kelvin\n",
      argv[0]
    );
    exit(EXIT_FAILURE);
  }
  float mired = atof(argv[1]);

  float rgb[N_RGB];
  mired_to_rgb(mired, rgb);
  printf(
    "mired %.3f -> RGB (%.6f, %.6f, %.6f)\n",
    mired,
    rgb[RGB_RED],
    rgb[RGB_GREEN],
    rgb[RGB_BLUE]
  );

  return EXIT_SUCCESS;
}
#endif
