#!/usr/bin/env python3
# generated by ../prepare/uv_to_rgb_gen_py.py

# Copyright (c) 2020 Nick Downing
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import numpy

# new way: (faster, at least up to interpreter overhead)
from gamma_encode import gamma_encode

UVL_U = 0
UVL_V = 1
UVL_L = 2
N_UVL = 3

# this is precomputed for the particular primaries in use
UVL_to_rgb = numpy.array(
  [
    [1.5534225814599655e+01, 2.9047739328113171e+00, -3.0310684516292001e+00],
    [-4.4821975170969814e+00, 5.0704930531059027e+00, 2.5261433074270867e-01],
    [-1.3527071050940691e+00, -1.6683387629493524e+01, 6.4253587491968300e+00]
  ],
  numpy.double
)

def uv_to_rgb(uv):
  # convert (u, v) to (R, G, B) in an optimized way
  # usually we would calculate w such that u + v + w = 1 and then take
  # (u, v, w) as (U, V, W) noting that brightness is arbitrary, and then
  # multiply through by a UVW -> rgb conversion matrix, but the matrix
  # used here expects L = U + V + W instead of W and L is always 1 here
  rgb = UVL_to_rgb[:, UVL_L] + UVL_to_rgb[:, :UVL_L] @ uv

  # low Kelvins are outside the gamut of SRGB and thus must be interpreted,
  # in this simplistic approach we simply clip off the negative blue value
  rgb[rgb < 0.] = 0.

  # normalize the brightness, so that at least one of R, G, or B = 1
  rgb /= numpy.max(rgb)

  # gamma-encode the R, G, B tuple according to the SRGB gamma curve
  # because displaying it on a monitor will gamma-decode it in the process

  # old way: (slower)
  #mask = rgb < .0031308
  #rgb[mask] *= 12.92
  #rgb[~mask] = rgb[~mask] ** (1. / 2.4) * 1.055 - 0.055

  # new way: (faster, at least up to interpreter overhead)
  for i in range(N_RGB):
    rgb[i] = gamma_encode(rgb[i])

  return rgb

if __name__ == '__main__':
  import sys

  EXIT_SUCCESS = 0
  EXIT_FAILURE = 1

  UV_u = 0
  UV_v = 1
  N_UV = 2

  RGB_RED = 0
  RGB_GREEN = 1
  RGB_BLUE = 2
  N_RGB = 3

  if len(sys.argv) < 3:
    print(f'usage: {sys.argv[0]:s} u v')
    print('u = CIE 1960 u coordinate')
    print('v = CIE 1960 v coordinate')
    sys.exit(EXIT_FAILURE)
  uv = [float(i) for i in sys.argv[1:3]]

  rgb = uv_to_rgb(uv)
  print(
    f'uv ({uv[UV_u]:.6f}, {uv[UV_v]:.6f}) -> RGB ({rgb[RGB_RED]:.6f}, {rgb[RGB_GREEN]:.6f}, {rgb[RGB_BLUE]:.6f})'
  )
